-- Seed the built-in trade taxonomy (organisation_id NULL = global built-in).
-- Mirrors docs/TRADES_TAXONOMY.md. Orgs can add their own ("Other") on top.
-- statutory = true means jobs in that trade carry a statutory inspection cert.

INSERT INTO trades (organisation_id, name, group_name, statutory) VALUES
  (NULL, 'Heating & boilers',                 'Mechanical & HVAC', true),
  (NULL, 'Ventilation & ductwork',            'Mechanical & HVAC', false),
  (NULL, 'Air conditioning & refrigeration',  'Mechanical & HVAC', true),
  (NULL, 'Chillers & cooling towers',         'Mechanical & HVAC', false),
  (NULL, 'BMS / building controls',           'Mechanical & HVAC', false),
  (NULL, 'Plumbing & sanitaryware',           'Mechanical & HVAC', false),
  (NULL, 'Hot water (calorifiers)',           'Mechanical & HVAC', false),
  (NULL, 'Pumps & pressurisation',            'Mechanical & HVAC', false),
  (NULL, 'Commercial gas services',           'Mechanical & HVAC', true),
  (NULL, 'Compressed air',                    'Mechanical & HVAC', false),
  (NULL, 'General electrical',                'Electrical & power', false),
  (NULL, 'Fixed-wire testing (EICR)',         'Electrical & power', true),
  (NULL, 'Portable appliance testing (PAT)',  'Electrical & power', true),
  (NULL, 'Lighting',                          'Electrical & power', false),
  (NULL, 'Emergency lighting',                'Electrical & power', true),
  (NULL, 'Standby generators',                'Electrical & power', false),
  (NULL, 'UPS & battery systems',             'Electrical & power', false),
  (NULL, 'Switchgear / distribution',         'Electrical & power', false),
  (NULL, 'Lightning protection',              'Electrical & power', true),
  (NULL, 'EV charge points',                  'Electrical & power', false),
  (NULL, 'Solar PV / renewables',             'Electrical & power', false),
  (NULL, 'Lifts / elevators',                 'Vertical transport', true),
  (NULL, 'Escalators & moving walkways',      'Vertical transport', true),
  (NULL, 'Platform lifts / hoists',           'Vertical transport', true),
  (NULL, 'Dock levellers',                    'Vertical transport', false),
  (NULL, 'Fire detection & alarms',           'Fire & life safety', true),
  (NULL, 'Fire extinguishers',                'Fire & life safety', true),
  (NULL, 'Sprinklers / suppression',          'Fire & life safety', true),
  (NULL, 'Dry & wet risers',                  'Fire & life safety', true),
  (NULL, 'Fire damper testing',               'Fire & life safety', true),
  (NULL, 'Smoke ventilation / AOV',           'Fire & life safety', false),
  (NULL, 'Fire doors',                        'Fire & life safety', true),
  (NULL, 'Passive fire protection',           'Fire & life safety', false),
  (NULL, 'Fire risk assessment',              'Fire & life safety', true),
  (NULL, 'Access control',                    'Security & access', false),
  (NULL, 'CCTV / surveillance',               'Security & access', false),
  (NULL, 'Intruder alarms',                   'Security & access', false),
  (NULL, 'Door entry / intercom',             'Security & access', false),
  (NULL, 'Automatic doors & shutters',        'Security & access', false),
  (NULL, 'Manned guarding',                   'Security & access', false),
  (NULL, 'Legionella / water hygiene',        'Water & drainage', true),
  (NULL, 'Water treatment',                   'Water & drainage', false),
  (NULL, 'Drainage / jetting',                'Water & drainage', false),
  (NULL, 'Leak detection',                    'Water & drainage', false),
  (NULL, 'Pumping stations',                  'Water & drainage', false),
  (NULL, 'Grease traps',                      'Water & drainage', false),
  (NULL, 'Roofing & gutters',                 'Building fabric & finishes', false),
  (NULL, 'Glazing / windows',                 'Building fabric & finishes', false),
  (NULL, 'Painting & decorating',             'Building fabric & finishes', false),
  (NULL, 'Plastering / rendering',            'Building fabric & finishes', false),
  (NULL, 'Carpentry & joinery',               'Building fabric & finishes', false),
  (NULL, 'Flooring',                          'Building fabric & finishes', false),
  (NULL, 'Masonry / brickwork',               'Building fabric & finishes', false),
  (NULL, 'Ceilings & partitions',             'Building fabric & finishes', false),
  (NULL, 'Locksmith',                         'Building fabric & finishes', false),
  (NULL, 'Signage',                           'Building fabric & finishes', false),
  (NULL, 'Fencing & gates',                   'Building fabric & finishes', false),
  (NULL, 'Metalwork / welding',               'Building fabric & finishes', false),
  (NULL, 'Waterproofing / damp-proofing',     'Building fabric & finishes', false),
  (NULL, 'Asbestos survey / removal',         'Building fabric & finishes', true),
  (NULL, 'Catering / kitchen + extract (TR19)','Specialist equipment', true),
  (NULL, 'Cold rooms / refrigeration',        'Specialist equipment', true),
  (NULL, 'Swimming pool / spa plant',         'Specialist equipment', false),
  (NULL, 'Lab equipment / fume cupboards (LEV)','Specialist equipment', true),
  (NULL, 'Medical gas',                       'Specialist equipment', false),
  (NULL, 'High-level access / window cleaning','Specialist equipment', false),
  (NULL, 'Cleaning / janitorial',             'Soft FM & grounds', false),
  (NULL, 'Grounds / landscaping',             'Soft FM & grounds', false),
  (NULL, 'Pest control',                      'Soft FM & grounds', false),
  (NULL, 'Waste management',                  'Soft FM & grounds', false),
  (NULL, 'Winter gritting',                   'Soft FM & grounds', false),
  (NULL, 'Washroom services',                 'Soft FM & grounds', false);
